############################################################
# Launcher for Command-line bootcamp container for the eBioKit
# This is a template, the following values must be replaced:
#   - $${INSTANCE_NAME}, name for the instance
#   - $${INSTANCE_PORT_1}, port number for terminal provider instance
#   - $${INSTANCE_PORT_2}, port number for the client website instance
############################################################

version: '2'
services:

    $${INSTANCE_NAME}-command-line-bootcamp-docker:
      image: docker:1.8-dind
      container_name: $${INSTANCE_NAME}-command-line-bootcamp-docker
      privileged: true

    $${INSTANCE_NAME}-command-line-bootcamp-term:
      image: fikipollo/command-line-bootcamp:term
      container_name: $${INSTANCE_NAME}-command-line-bootcamp-term
      links:
        - $${INSTANCE_NAME}-command-line-bootcamp-docker:docker
      depends_on:
        - $${INSTANCE_NAME}-command-line-bootcamp-docker
      ports:
        - "$${INSTANCE_PORT_2}:8080"

    $${INSTANCE_NAME}-command-line-bootcamp-web:
      image: fikipollo/command-line-bootcamp:web
      container_name: $${INSTANCE_NAME}-command-line-bootcamp-web
      ports:
        - "$${INSTANCE_PORT_1}:80"
      environment:
        - SERVER_URL=/$${INSTANCE_NAME}-term
