############################################################
# Dockerfile to build code bootcamp server application images
# Based on ubuntu
############################################################

# Set the base image to official Ubuntu image
FROM ubuntu:14.04

# File Author / Maintainer
MAINTAINER Rafa Hernandez <rafahd87@gmail.com>

################## BEGIN INSTALLATION ######################

RUN apt-get update && apt-get install -y build-essential g++ curl git python vim npm docker.io

RUN ln -s /usr/bin/nodejs /usr/bin/node 
#\
#    && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash

#bash -l -c "source ~/.bashrc" \
#    && bash -l -c "nvm install 0.12" \
#    && bash -l -c "nvm use 0.12" \

RUN  npm install --global docker-browser-server \
    && cd /usr/local/ \
    && git clone https://github.com/Blahah/command_line_bootcamp.git

#RUN bash -l -c "docker -d &" \
#    && cd /usr/local/command_line_bootcamp \
#    && docker build -t "command_line_bootcamp" .

COPY configs/entrypoint.sh /usr/bin/entrypoint.sh

RUN chmod +x /usr/bin/entrypoint.sh

##################### INSTALLATION END #####################

# Expose port 8080 (docker-browser-server)
EXPOSE :8080

ENTRYPOINT ["/usr/bin/entrypoint.sh"]

